# fly.toml app configuration file generated for peated-api on 2023-05-06T10:56:06-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "peated-faktory"
primary_region = "den"

[env]
FAKTORY_ENV="production"

[build]
image = "contribsys/faktory:latest"

[[services]]
  http_checks = []
  internal_port = 7420
  processes = []
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    handlers = []
    port = 7419
    
  [[services.ports]]
    handlers = ["http"]
    port = 7420

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
