name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  migrate:
    name: DB Migrations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm rum prisma migrate deploy -w apps/api
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: make deploy-api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN_API }}
      - run: make deploy-web
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_TOKEN_WEB }}
